python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=46774 +evaluation.fold_idx=1
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=11129 +evaluation.fold_idx=2
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=11129 +evaluation.fold_idx=2
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=5111 +evaluation.fold_idx=6
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=5111 +evaluation.fold_idx=6
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=54277 +evaluation.fold_idx=1
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=5111 +evaluation.fold_idx=3
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=24539 +evaluation.fold_idx=3
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=46774 +evaluation.fold_idx=4
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=33478 +evaluation.fold_idx=0
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=33478 +evaluation.fold_idx=4
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=5111 +evaluation.fold_idx=0
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=11129 +evaluation.fold_idx=1
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=5111 +evaluation.fold_idx=2
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=24539 +evaluation.fold_idx=4
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=46774 +evaluation.fold_idx=0
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=46774 +evaluation.fold_idx=3
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=46774 +evaluation.fold_idx=5
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=5111 +evaluation.fold_idx=4
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=46774 +evaluation.fold_idx=2
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=46774 +evaluation.fold_idx=4
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=33478 +evaluation.fold_idx=5
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=5111 +evaluation.fold_idx=2
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=5111 +evaluation.fold_idx=4
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=5111 +evaluation.fold_idx=1
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=11129 +evaluation.fold_idx=5
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=54277 +evaluation.fold_idx=2
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=54277 +evaluation.fold_idx=0
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=24539 +evaluation.fold_idx=2
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=5111 +evaluation.fold_idx=0
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=5111 +evaluation.fold_idx=3
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=33478 +evaluation.fold_idx=3
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=33478 +evaluation.fold_idx=2
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=24539 +evaluation.fold_idx=2
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=54277 +evaluation.fold_idx=1
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=46774 +evaluation.fold_idx=2
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=11129 +evaluation.fold_idx=0
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=54277 +evaluation.fold_idx=4
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=46774 +evaluation.fold_idx=4
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=24539 +evaluation.fold_idx=6
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=24539 +evaluation.fold_idx=2
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=54277 +evaluation.fold_idx=4
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=46774 +evaluation.fold_idx=1
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=24539 +evaluation.fold_idx=6
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=46774 +evaluation.fold_idx=3
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=5111 +evaluation.fold_idx=6
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=24539 +evaluation.fold_idx=5
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=46774 +evaluation.fold_idx=3
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=46774 +evaluation.fold_idx=4
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=11129 +evaluation.fold_idx=4
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=11129 +evaluation.fold_idx=0
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=5111 +evaluation.fold_idx=3
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=33478 +evaluation.fold_idx=0
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=54277 +evaluation.fold_idx=6
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=11129 +evaluation.fold_idx=5
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=5111 +evaluation.fold_idx=6
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=24539 +evaluation.fold_idx=0
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=33478 +evaluation.fold_idx=4
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=54277 +evaluation.fold_idx=5
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=11129 +evaluation.fold_idx=6
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=11129 +evaluation.fold_idx=0
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=46774 +evaluation.fold_idx=0
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=11129 +evaluation.fold_idx=4
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=33478 +evaluation.fold_idx=6
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=54277 +evaluation.fold_idx=6
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=46774 +evaluation.fold_idx=5
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=24539 +evaluation.fold_idx=2
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=5111 +evaluation.fold_idx=1
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=5111 +evaluation.fold_idx=0
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=54277 +evaluation.fold_idx=1
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=54277 +evaluation.fold_idx=6
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=33478 +evaluation.fold_idx=3
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=11129 +evaluation.fold_idx=6
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=46774 +evaluation.fold_idx=6
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=46774 +evaluation.fold_idx=0
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=33478 +evaluation.fold_idx=3
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=54277 +evaluation.fold_idx=3
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=33478 +evaluation.fold_idx=2
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=46774 +evaluation.fold_idx=4
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=11129 +evaluation.fold_idx=4
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=46774 +evaluation.fold_idx=3
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=33478 +evaluation.fold_idx=0
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=46774 +evaluation.fold_idx=0
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=5111 +evaluation.fold_idx=5
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=24539 +evaluation.fold_idx=3
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=33478 +evaluation.fold_idx=6
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=5111 +evaluation.fold_idx=4
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=24539 +evaluation.fold_idx=5
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=11129 +evaluation.fold_idx=3
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=24539 +evaluation.fold_idx=5
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=24539 +evaluation.fold_idx=6
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=11129 +evaluation.fold_idx=1
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=11129 +evaluation.fold_idx=0
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=46774 +evaluation.fold_idx=2
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=11129 +evaluation.fold_idx=6
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=11129 +evaluation.fold_idx=1
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=54277 +evaluation.fold_idx=0
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=46774 +evaluation.fold_idx=0
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=5111 +evaluation.fold_idx=2
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=46774 +evaluation.fold_idx=3
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=33478 +evaluation.fold_idx=4
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=33478 +evaluation.fold_idx=5
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=33478 +evaluation.fold_idx=0
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=33478 +evaluation.fold_idx=3
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=11129 +evaluation.fold_idx=6
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=5111 +evaluation.fold_idx=2
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=33478 +evaluation.fold_idx=4
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=5111 +evaluation.fold_idx=1
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=54277 +evaluation.fold_idx=1
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=5111 +evaluation.fold_idx=5
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=24539 +evaluation.fold_idx=4
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=5111 +evaluation.fold_idx=6
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=11129 +evaluation.fold_idx=5
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=54277 +evaluation.fold_idx=1
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=5111 +evaluation.fold_idx=2
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=33478 +evaluation.fold_idx=5
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=46774 +evaluation.fold_idx=1
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=11129 +evaluation.fold_idx=3
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=24539 +evaluation.fold_idx=0
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=46774 +evaluation.fold_idx=5
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=11129 +evaluation.fold_idx=0
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=24539 +evaluation.fold_idx=1
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=54277 +evaluation.fold_idx=4
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=54277 +evaluation.fold_idx=6
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=11129 +evaluation.fold_idx=6
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=5111 +evaluation.fold_idx=3
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=24539 +evaluation.fold_idx=3
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=24539 +evaluation.fold_idx=5
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=46774 +evaluation.fold_idx=6
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=11129 +evaluation.fold_idx=6
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=5111 +evaluation.fold_idx=5
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=5111 +evaluation.fold_idx=0
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=33478 +evaluation.fold_idx=4
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=33478 +evaluation.fold_idx=1
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=54277 +evaluation.fold_idx=6
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=54277 +evaluation.fold_idx=0
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=54277 +evaluation.fold_idx=5
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=11129 +evaluation.fold_idx=4
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=54277 +evaluation.fold_idx=5
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=46774 +evaluation.fold_idx=4
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=24539 +evaluation.fold_idx=4
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=46774 +evaluation.fold_idx=0
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=33478 +evaluation.fold_idx=1
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=5111 +evaluation.fold_idx=6
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=24539 +evaluation.fold_idx=5
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=11129 +evaluation.fold_idx=5
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=5111 +evaluation.fold_idx=3
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=5111 +evaluation.fold_idx=2
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=24539 +evaluation.fold_idx=1
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=11129 +evaluation.fold_idx=4
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=54277 +evaluation.fold_idx=6
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=11129 +evaluation.fold_idx=4
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=54277 +evaluation.fold_idx=4
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=5111 +evaluation.fold_idx=1
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=11129 +evaluation.fold_idx=5
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=33478 +evaluation.fold_idx=6
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=33478 +evaluation.fold_idx=5
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=5111 +evaluation.fold_idx=5
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=11129 +evaluation.fold_idx=2
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=24539 +evaluation.fold_idx=0
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=33478 +evaluation.fold_idx=1
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=33478 +evaluation.fold_idx=1
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=11129 +evaluation.fold_idx=2
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=24539 +evaluation.fold_idx=5
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=54277 +evaluation.fold_idx=6
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=24539 +evaluation.fold_idx=1
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=54277 +evaluation.fold_idx=3
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=33478 +evaluation.fold_idx=5
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=11129 +evaluation.fold_idx=1
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=24539 +evaluation.fold_idx=6
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=46774 +evaluation.fold_idx=5
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=54277 +evaluation.fold_idx=1
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=24539 +evaluation.fold_idx=3
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=24539 +evaluation.fold_idx=6
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=24539 +evaluation.fold_idx=2
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=54277 +evaluation.fold_idx=3
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=5111 +evaluation.fold_idx=2
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=5111 +evaluation.fold_idx=3
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=5111 +evaluation.fold_idx=5
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=5111 +evaluation.fold_idx=0
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=46774 +evaluation.fold_idx=1
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=11129 +evaluation.fold_idx=1
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=46774 +evaluation.fold_idx=2
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=46774 +evaluation.fold_idx=5
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=54277 +evaluation.fold_idx=1
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=33478 +evaluation.fold_idx=3
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=33478 +evaluation.fold_idx=6
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=54277 +evaluation.fold_idx=5
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=46774 +evaluation.fold_idx=6
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=33478 +evaluation.fold_idx=3
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=54277 +evaluation.fold_idx=0
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=24539 +evaluation.fold_idx=1
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=33478 +evaluation.fold_idx=5
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=46774 +evaluation.fold_idx=2
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=54277 +evaluation.fold_idx=2
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=46774 +evaluation.fold_idx=1
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=46774 +evaluation.fold_idx=0
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=46774 +evaluation.fold_idx=6
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=24539 +evaluation.fold_idx=6
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=5111 +evaluation.fold_idx=4
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=46774 +evaluation.fold_idx=3
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=24539 +evaluation.fold_idx=3
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=46774 +evaluation.fold_idx=6
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=46774 +evaluation.fold_idx=6
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=11129 +evaluation.fold_idx=2
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=11129 +evaluation.fold_idx=2
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=24539 +evaluation.fold_idx=6
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=54277 +evaluation.fold_idx=5
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=33478 +evaluation.fold_idx=6
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=33478 +evaluation.fold_idx=3
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=54277 +evaluation.fold_idx=4
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=11129 +evaluation.fold_idx=1
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=46774 +evaluation.fold_idx=6
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=46774 +evaluation.fold_idx=2
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=46774 +evaluation.fold_idx=5
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=46774 +evaluation.fold_idx=5
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=24539 +evaluation.fold_idx=0
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=24539 +evaluation.fold_idx=4
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=5111 +evaluation.fold_idx=0
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=33478 +evaluation.fold_idx=0
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=33478 +evaluation.fold_idx=1
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=24539 +evaluation.fold_idx=1
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=46774 +evaluation.fold_idx=4
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=5111 +evaluation.fold_idx=6
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=5111 +evaluation.fold_idx=3
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=33478 +evaluation.fold_idx=6
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=5111 +evaluation.fold_idx=2
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=5111 +evaluation.fold_idx=5
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=33478 +evaluation.fold_idx=0
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=11129 +evaluation.fold_idx=1
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=11129 +evaluation.fold_idx=5
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=24539 +evaluation.fold_idx=4
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=33478 +evaluation.fold_idx=5
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=54277 +evaluation.fold_idx=2
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=5111 +evaluation.fold_idx=0
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=5111 +evaluation.fold_idx=1
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=24539 +evaluation.fold_idx=2
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=54277 +evaluation.fold_idx=2
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=33478 +evaluation.fold_idx=2
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=54277 +evaluation.fold_idx=0
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=54277 +evaluation.fold_idx=1
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=46774 +evaluation.fold_idx=5
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=24539 +evaluation.fold_idx=3
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=46774 +evaluation.fold_idx=4
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=24539 +evaluation.fold_idx=1
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=5111 +evaluation.fold_idx=4
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=11129 +evaluation.fold_idx=3
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=33478 +evaluation.fold_idx=6
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=5111 +evaluation.fold_idx=3
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=24539 +evaluation.fold_idx=4
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=11129 +evaluation.fold_idx=5
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=11129 +evaluation.fold_idx=0
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=5111 +evaluation.fold_idx=0
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=11129 +evaluation.fold_idx=3
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=33478 +evaluation.fold_idx=6
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=54277 +evaluation.fold_idx=6
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=24539 +evaluation.fold_idx=0
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=54277 +evaluation.fold_idx=0
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=33478 +evaluation.fold_idx=1
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=54277 +evaluation.fold_idx=0
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=5111 +evaluation.fold_idx=1
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=33478 +evaluation.fold_idx=2
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=11129 +evaluation.fold_idx=6
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=5111 +evaluation.fold_idx=4
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=5111 +evaluation.fold_idx=1
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=24539 +evaluation.fold_idx=3
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=46774 +evaluation.fold_idx=3
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=11129 +evaluation.fold_idx=3
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=54277 +evaluation.fold_idx=3
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=33478 +evaluation.fold_idx=2
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=11129 +evaluation.fold_idx=0
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=5111 +evaluation.fold_idx=5
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=24539 +evaluation.fold_idx=1
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=11129 +evaluation.fold_idx=4
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=11129 +evaluation.fold_idx=6
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=11129 +evaluation.fold_idx=4
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=11129 +evaluation.fold_idx=2
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=11129 +evaluation.fold_idx=2
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=54277 +evaluation.fold_idx=5
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=24539 +evaluation.fold_idx=3
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=46774 +evaluation.fold_idx=2
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=54277 +evaluation.fold_idx=3
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=33478 +evaluation.fold_idx=1
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=5111 +evaluation.fold_idx=4
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=54277 +evaluation.fold_idx=2
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=11129 +evaluation.fold_idx=3
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=46774 +evaluation.fold_idx=6
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=11129 +evaluation.fold_idx=3
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=24539 +evaluation.fold_idx=5
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=24539 +evaluation.fold_idx=5
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=46774 +evaluation.fold_idx=1
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=5111 +evaluation.fold_idx=1
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=46774 +evaluation.fold_idx=1
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=33478 +evaluation.fold_idx=3
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=11129 +evaluation.fold_idx=1
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=24539 +evaluation.fold_idx=0
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=24539 +evaluation.fold_idx=6
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=54277 +evaluation.fold_idx=2
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=33478 +evaluation.fold_idx=4
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=54277 +evaluation.fold_idx=2
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=33478 +evaluation.fold_idx=0
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=54277 +evaluation.fold_idx=3
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=5111 +evaluation.fold_idx=5
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=24539 +evaluation.fold_idx=4
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=33478 +evaluation.fold_idx=0
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=54277 +evaluation.fold_idx=5
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=46774 +evaluation.fold_idx=2
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=33478 +evaluation.fold_idx=4
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=54277 +evaluation.fold_idx=2
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=46774 +evaluation.fold_idx=0
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=54277 +evaluation.fold_idx=4
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=24539 +evaluation.fold_idx=1
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=5111 +evaluation.fold_idx=4
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=24539 +evaluation.fold_idx=0
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=24539 +evaluation.fold_idx=4
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=46774 +evaluation.fold_idx=1
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=33478 +evaluation.fold_idx=1
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=33478 +evaluation.fold_idx=4
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=54277 +evaluation.fold_idx=3
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=33478 +evaluation.fold_idx=2
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=33478 +evaluation.fold_idx=5
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=33478 +evaluation.fold_idx=2
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=24539 +evaluation.fold_idx=2
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=11129 +evaluation.fold_idx=5
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=54277 +evaluation.fold_idx=4
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=11129 +evaluation.fold_idx=0
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=5111 +evaluation.fold_idx=6
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=54277 +evaluation.fold_idx=0
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=54277 +evaluation.fold_idx=5
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=11129 +evaluation.fold_idx=3
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=46774 +evaluation.fold_idx=3
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=54277 +evaluation.fold_idx=4
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=33478 +evaluation.fold_idx=2
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=54277 +evaluation.fold_idx=3
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=24539 +evaluation.fold_idx=2
python3 main.py data=adl_10s evaluation=finetune_ensemble +evaluation.seed=24539 +evaluation.fold_idx=0